[package]
name = "fibonacci"
version = "0.2.0"
authors = ["Evelyn Fitzgerald <acf67@cornell.edu>"]
edition = "2018"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
